name: CI 
on: 
  push: 
    branches: [master] 
  pull_request: 
    branches: [master] 
jobs: 
  build: 
    runs-on: ubuntu-latest 
    steps: 
      - name: Checkout repository 
        uses: actions/checkout@v4
      - name: Setup Java JDK
        uses: actions/setup-java@v3.14.1
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Cache files 
        uses: actions/cache@v4
        with: 
            path: | 
                ~/.sonar 
            key: ${{ runner.os }}-sonar 
            restore-keys: ${{ runner.os }}-sonar 
      - name: Run Codescan On Push 
        if: github.event_name == 'push' 
        uses: codescan-io/codescan-scanner-action@cd6610
        with: 
          codeScanUrl: https://app.codescan.io
          organization: prod-raj1 
          projectKey: fkk
          login: squ_be15755f4d057d9873810562e25e68f9b9d60e72
          failOnRedQualityGate: false 
      - name: Run Codescan On PR 
        if: github.event_name == 'pull_request' 
        uses: codescan-io/codescan-scanner-action@cd6610
        with: 
          codeScanUrl: https://app.codescan.io
          organization: prod-raj1
          projectKey: fkk
          login: squ_be15755f4d057d9873810562e25e68f9b9d60e72
          scanChangedFilesOnly: true 
          failOnRedQualityGate: false
          args: | 
            sonar.pullrequest.branch=${{github.head_ref}} 
            sonar.pullrequest.base=${{github.base_ref}} 
            sonar.pullrequest.key=${{github.event.number}} 
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
            name: codescan.sarif
            path: codescan.sarif 
