name: CI 
on: 
  push: 
    branches: [master] 
  pull_request: 
    branches: [master] 
jobs: 
  build: 
    runs-on: ubuntu-latest 
    steps: 
      - name: Checkout repository 
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # or the version you need
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Verify Java installation
        run: java -version
      - name: Set JAVA_HOME environment variable
        run: echo "JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))" >> $GITHUB_ENV
      - name: Cache files 
        uses: actions/cache@v4
        with: 
            path: | 
                ~/.sonar 
            key: ${{ runner.os }}-sonar 
            restore-keys: ${{ runner.os }}-sonar      
      - name: Run Codescan On Push 
        if: github.event_name == 'push' 
        uses: codescan-io/codescan-scanner-action@1.6
        with: 
          codeScanUrl: https://test.codescan.io
          organization: shekar-org1
          projectKey: ncino-sf
          login: squ_67e11b2ad3cee4458f5c1b375f837701114976c0
          failOnRedQualityGate: false 
      - name: Run Codescan On PR 
        if: github.event_name == 'pull_request' 
        uses: codescan-io/codescan-scanner-action@1.6
        with: 
          codeScanUrl: https://test.codescan.io
          organization: shekar-org1
          projectKey: ncino-sf
          login: squ_67e11b2ad3cee4458f5c1b375f837701114976c0
          scanChangedFilesOnly: true 
          failOnRedQualityGate: false
          args: | 
            sonar.pullrequest.branch=${{github.head_ref}} 
            sonar.pullrequest.base=${{github.base_ref}} 
            sonar.pullrequest.key=${{github.event.number}} 
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
            name: codescan.sarif
            path: codescan.sarif 
